package tables

// This file was generated by rip.go.  Functionally editing it is probably a bad idea; go fmt-ing it is fine.
// It contains quadrant, system and info data, plus autogenerated ID constants
// IDs are generated by forcing in-game names to uppercase then replacing anything not alphanumeric with "_",
// which is mostly fine but does result in some clunktastic IDs like  "BASE_TUCK_S" and "SYS_HIND_S_VARIABLE_N_"

type QUAD_ID uint8
type SYS_ID uint8
type BASE_ID uint8
type BASE_TYPE uint8

const (
	QUAD_HUMBOLDT QUAD_ID = 0
	QUAD_FARISS   QUAD_ID = 1
	QUAD_POTTER   QUAD_ID = 2
	QUAD_CLARKE   QUAD_ID = 3
)

// The strange order here is quadrant first, then ASCIIbetical
const (
	SYS_CM_N1054               SYS_ID = 10
	SYS_FREYJA                 SYS_ID = 16
	SYS_119CE                  SYS_ID = 19
	SYS_JUNCTION               SYS_ID = 21
	SYS_PADRE                  SYS_ID = 38
	SYS_PENDER_S_STAR          SYS_ID = 40
	SYS_PENTONVILLE            SYS_ID = 41
	SYS_POLLUX                 SYS_ID = 44
	SYS_PRASEPE                SYS_ID = 45
	SYS_PYRENEES               SYS_ID = 46
	SYS_TROY                   SYS_ID = 58
	SYS_VARNUS                 SYS_ID = 64
	SYS_17_AR                  SYS_ID = 0
	SYS_CAPELLA                SYS_ID = 8
	SYS_CASTOR                 SYS_ID = 9
	SYS_CRAB_12                SYS_ID = 12
	SYS_DEATH                  SYS_ID = 13
	SYS_FAMINE                 SYS_ID = 15
	SYS_J900                   SYS_ID = 20
	SYS_KM_252                 SYS_ID = 25
	SYS_NEW_CALEDONIA          SYS_ID = 31
	SYS_NEXUS                  SYS_ID = 35
	SYS_PALAN                  SYS_ID = 39
	SYS_PESTILENCE             SYS_ID = 43
	SYS_REGALLIS               SYS_ID = 49
	SYS_RYGANNON               SYS_ID = 51
	SYS_SHERWOOD               SYS_ID = 54
	SYS_TELAR                  SYS_ID = 56
	SYS_DELTA                  SYS_ID = 59
	SYS_GAMMA                  SYS_ID = 60
	SYS_BETA                   SYS_ID = 61
	SYS_DELTA_PRIME            SYS_ID = 62
	SYS_VALHALLA               SYS_ID = 63
	SYS_WAR                    SYS_ID = 65
	SYS_XYTANI                 SYS_ID = 66
	SYS__TESTBED_              SYS_ID = 68
	SYS_41_GS                  SYS_ID = 1
	SYS_44_P_IM                SYS_ID = 2
	SYS_ALDEBRAN               SYS_ID = 3
	SYS_AURIGA                 SYS_ID = 4
	SYS_DN_N1912               SYS_ID = 14
	SYS_HIND_S_VARIABLE_N_     SYS_ID = 17
	SYS_MANCHESTER             SYS_ID = 27
	SYS_METSOR                 SYS_ID = 28
	SYS_ND_57                  SYS_ID = 30
	SYS_NEWCASTLE              SYS_ID = 32
	SYS_NEW_CONSTANTINOPLE     SYS_ID = 33
	SYS_NEW_DETROIT            SYS_ID = 34
	SYS_OXFORD                 SYS_ID = 37
	SYS_RAXIS                  SYS_ID = 48
	SYS_SAXTOGUE               SYS_ID = 52
	SYS_SHANGRI_LA             SYS_ID = 53
	SYS_XXN_1927               SYS_ID = 67
	SYS_BLOCKADE_POINT_ALPHA   SYS_ID = 5
	SYS_BLOCKADE_POINT_CHARLIE SYS_ID = 6
	SYS_BLOCKADE_POINT_TANGO   SYS_ID = 7
	SYS_CMF_A                  SYS_ID = 11
	SYS_HYADES                 SYS_ID = 18
	SYS_TR_PAKH                SYS_ID = 22
	SYS_SUMN_KP_TA             SYS_ID = 23
	SYS_MAH_RAHN               SYS_ID = 24
	SYS_LISACC                 SYS_ID = 26
	SYS_MIDGARD                SYS_ID = 29
	SYS_NITIR                  SYS_ID = 36
	SYS_PERRY                  SYS_ID = 42
	SYS_RAGNAROK               SYS_ID = 47
	SYS_RIKEL                  SYS_ID = 50
	SYS_SURTUR                 SYS_ID = 55
	SYS_TINGERHOFF             SYS_ID = 57
)

type Sysinfo struct {
	Name     string
	Quadrant QUAD_ID
	Bases    []BASE_ID
}

var systems = map[SYS_ID]Sysinfo{
	SYS_CM_N1054:               Sysinfo{Name: "CM-N1054", Quadrant: 0},
	SYS_FREYJA:                 Sysinfo{Name: "Freyja", Quadrant: 0},
	SYS_119CE:                  Sysinfo{Name: "119CE", Quadrant: 0},
	SYS_JUNCTION:               Sysinfo{Name: "Junction", Quadrant: 0, Bases: []BASE_ID{6, 50, 56}},
	SYS_PADRE:                  Sysinfo{Name: "Padre", Quadrant: 0, Bases: []BASE_ID{24}},
	SYS_PENDER_S_STAR:          Sysinfo{Name: "Pender's Star", Quadrant: 0},
	SYS_PENTONVILLE:            Sysinfo{Name: "Pentonville", Quadrant: 0, Bases: []BASE_ID{36}},
	SYS_POLLUX:                 Sysinfo{Name: "Pollux", Quadrant: 0, Bases: []BASE_ID{42}},
	SYS_PRASEPE:                Sysinfo{Name: "Prasepe", Quadrant: 0, Bases: []BASE_ID{47}},
	SYS_PYRENEES:               Sysinfo{Name: "Pyrenees", Quadrant: 0, Bases: []BASE_ID{2, 33}},
	SYS_TROY:                   Sysinfo{Name: "Troy", Quadrant: 0, Bases: []BASE_ID{0, 15, 17}},
	SYS_VARNUS:                 Sysinfo{Name: "Varnus", Quadrant: 0, Bases: []BASE_ID{43, 44}},
	SYS_17_AR:                  Sysinfo{Name: "17-AR", Quadrant: 1},
	SYS_CAPELLA:                Sysinfo{Name: "Capella", Quadrant: 1, Bases: []BASE_ID{8}},
	SYS_CASTOR:                 Sysinfo{Name: "Castor", Quadrant: 1, Bases: []BASE_ID{45}},
	SYS_CRAB_12:                Sysinfo{Name: "Crab-12", Quadrant: 1},
	SYS_DEATH:                  Sysinfo{Name: "Death", Quadrant: 1},
	SYS_FAMINE:                 Sysinfo{Name: "Famine", Quadrant: 1},
	SYS_J900:                   Sysinfo{Name: "J900", Quadrant: 1},
	SYS_KM_252:                 Sysinfo{Name: "KM-252", Quadrant: 1, Bases: []BASE_ID{49}},
	SYS_NEW_CALEDONIA:          Sysinfo{Name: "New Caledonia", Quadrant: 1, Bases: []BASE_ID{9, 13}},
	SYS_NEXUS:                  Sysinfo{Name: "Nexus", Quadrant: 1, Bases: []BASE_ID{23}},
	SYS_PALAN:                  Sysinfo{Name: "Palan", Quadrant: 1, Bases: []BASE_ID{3, 40}},
	SYS_PESTILENCE:             Sysinfo{Name: "Pestilence", Quadrant: 1},
	SYS_REGALLIS:               Sysinfo{Name: "Regallis", Quadrant: 1, Bases: []BASE_ID{20}},
	SYS_RYGANNON:               Sysinfo{Name: "Rygannon", Quadrant: 1, Bases: []BASE_ID{46}},
	SYS_SHERWOOD:               Sysinfo{Name: "Sherwood", Quadrant: 1, Bases: []BASE_ID{54}},
	SYS_TELAR:                  Sysinfo{Name: "Telar", Quadrant: 1, Bases: []BASE_ID{27}},
	SYS_DELTA:                  Sysinfo{Name: "Delta", Quadrant: 1},
	SYS_GAMMA:                  Sysinfo{Name: "Gamma", Quadrant: 1},
	SYS_BETA:                   Sysinfo{Name: "Beta", Quadrant: 1},
	SYS_DELTA_PRIME:            Sysinfo{Name: "Delta Prime", Quadrant: 1, Bases: []BASE_ID{59}},
	SYS_VALHALLA:               Sysinfo{Name: "Valhalla", Quadrant: 1, Bases: []BASE_ID{55}},
	SYS_WAR:                    Sysinfo{Name: "War", Quadrant: 1},
	SYS_XYTANI:                 Sysinfo{Name: "Xytani", Quadrant: 1},
	SYS__TESTBED_:              Sysinfo{Name: "#Testbed#", Quadrant: 1},
	SYS_41_GS:                  Sysinfo{Name: "41-GS", Quadrant: 2},
	SYS_44_P_IM:                Sysinfo{Name: "44-P-IM", Quadrant: 2},
	SYS_ALDEBRAN:               Sysinfo{Name: "Aldebran", Quadrant: 2, Bases: []BASE_ID{25}},
	SYS_AURIGA:                 Sysinfo{Name: "Auriga", Quadrant: 2, Bases: []BASE_ID{4, 11}},
	SYS_DN_N1912:               Sysinfo{Name: "DN-N1912", Quadrant: 2, Bases: []BASE_ID{30}},
	SYS_HIND_S_VARIABLE_N_:     Sysinfo{Name: "Hind's Variable N.", Quadrant: 2, Bases: []BASE_ID{26, 38}},
	SYS_MANCHESTER:             Sysinfo{Name: "Manchester", Quadrant: 2, Bases: []BASE_ID{52, 58}},
	SYS_METSOR:                 Sysinfo{Name: "Metsor", Quadrant: 2},
	SYS_ND_57:                  Sysinfo{Name: "ND-57", Quadrant: 2, Bases: []BASE_ID{34}},
	SYS_NEWCASTLE:              Sysinfo{Name: "Newcastle", Quadrant: 2, Bases: []BASE_ID{22}},
	SYS_NEW_CONSTANTINOPLE:     Sysinfo{Name: "New Constantinople", Quadrant: 2, Bases: []BASE_ID{10, 31}},
	SYS_NEW_DETROIT:            Sysinfo{Name: "New Detroit", Quadrant: 2, Bases: []BASE_ID{32}},
	SYS_OXFORD:                 Sysinfo{Name: "Oxford", Quadrant: 2, Bases: []BASE_ID{39}},
	SYS_RAXIS:                  Sysinfo{Name: "Raxis", Quadrant: 2, Bases: []BASE_ID{14, 53}},
	SYS_SAXTOGUE:               Sysinfo{Name: "Saxtogue", Quadrant: 2, Bases: []BASE_ID{37}},
	SYS_SHANGRI_LA:             Sysinfo{Name: "Shangri La", Quadrant: 2, Bases: []BASE_ID{12}},
	SYS_XXN_1927:               Sysinfo{Name: "XXN-1927", Quadrant: 2, Bases: []BASE_ID{18, 19}},
	SYS_BLOCKADE_POINT_ALPHA:   Sysinfo{Name: "Blockade Point Alpha", Quadrant: 3},
	SYS_BLOCKADE_POINT_CHARLIE: Sysinfo{Name: "Blockade Point Charlie", Quadrant: 3},
	SYS_BLOCKADE_POINT_TANGO:   Sysinfo{Name: "Blockade Point Tango", Quadrant: 3},
	SYS_CMF_A:                  Sysinfo{Name: "CMF-A", Quadrant: 3},
	SYS_HYADES:                 Sysinfo{Name: "Hyades", Quadrant: 3, Bases: []BASE_ID{7}},
	SYS_TR_PAKH:                Sysinfo{Name: "Tr'Pakh", Quadrant: 3},
	SYS_SUMN_KP_TA:             Sysinfo{Name: "Sumn-Kp'ta", Quadrant: 3},
	SYS_MAH_RAHN:               Sysinfo{Name: "Mah'Rahn", Quadrant: 3},
	SYS_LISACC:                 Sysinfo{Name: "Lisacc", Quadrant: 3, Bases: []BASE_ID{21}},
	SYS_MIDGARD:                Sysinfo{Name: "Midgard", Quadrant: 3, Bases: []BASE_ID{16}},
	SYS_NITIR:                  Sysinfo{Name: "Nitir", Quadrant: 3, Bases: []BASE_ID{35}},
	SYS_PERRY:                  Sysinfo{Name: "Perry", Quadrant: 3, Bases: []BASE_ID{1, 41}},
	SYS_RAGNAROK:               Sysinfo{Name: "Ragnarok", Quadrant: 3, Bases: []BASE_ID{28}},
	SYS_RIKEL:                  Sysinfo{Name: "Rikel", Quadrant: 3, Bases: []BASE_ID{48, 57}},
	SYS_SURTUR:                 Sysinfo{Name: "Surtur", Quadrant: 3, Bases: []BASE_ID{51}},
	SYS_TINGERHOFF:             Sysinfo{Name: "Tingerhoff", Quadrant: 3, Bases: []BASE_ID{5, 29}},
}

const (
	BASE_ACHILLES           BASE_ID = 0
	BASE_ANAPOLIS           BASE_ID = 1
	BASE_BASQUE             BASE_ID = 2
	BASE_BASRA              BASE_ID = 3
	BASE_BEACONSFIELD       BASE_ID = 4
	BASE_BODENSEE           BASE_ID = 5
	BASE_BURTON             BASE_ID = 6
	BASE_CHARON             BASE_ID = 7
	BASE_DRAKE              BASE_ID = 8
	BASE_EDINBURGH          BASE_ID = 9
	BASE_EDOM               BASE_ID = 10
	BASE_ELYSIA             BASE_ID = 11
	BASE_EREWHON            BASE_ID = 12
	BASE_GLASGOW            BASE_ID = 13
	BASE_GRACCHUS           BASE_ID = 14
	BASE_HECTOR             BASE_ID = 15
	BASE_HEIMDEL            BASE_ID = 16
	BASE_HELEN              BASE_ID = 17
	BASE_JOLSON             BASE_ID = 18
	BASE_JOPLIN             BASE_ID = 19
	BASE_KRONECKER          BASE_ID = 20
	BASE_LISACC             BASE_ID = 21
	BASE_LIVERPOOL          BASE_ID = 22
	BASE_MACABEE            BASE_ID = 23
	BASE_MAGDALINE          BASE_ID = 24
	BASE_MATAHARI           BASE_ID = 25
	BASE_MEADOW             BASE_ID = 26
	BASE_MEGIDDO            BASE_ID = 27
	BASE_MJOLNAR            BASE_ID = 28
	BASE_MUNCHEN            BASE_ID = 29
	BASE_N1912_1            BASE_ID = 30
	BASE_NEW_CONSTANTINOPLE BASE_ID = 31
	BASE_NEW_DETROIT        BASE_ID = 32
	BASE_NEW_IBERIA         BASE_ID = 33
	BASE_NEW_RENO           BASE_ID = 34
	BASE_NITIR              BASE_ID = 35
	BASE_OAKHAM             BASE_ID = 36
	BASE_OLYMPUS            BASE_ID = 37
	BASE_ORESVILLE          BASE_ID = 38
	BASE_OXFORD             BASE_ID = 39
	BASE_PALAN              BASE_ID = 40
	BASE_PERRY_NAVAL_BASE   BASE_ID = 41
	BASE_REMUS              BASE_ID = 42
	BASE_RILKE              BASE_ID = 43
	BASE_RODIN              BASE_ID = 44
	BASE_ROMULUS            BASE_ID = 45
	BASE_RYGANNON           BASE_ID = 46
	BASE_SARATOV            BASE_ID = 47
	BASE_SIVA               BASE_ID = 48
	BASE_SMALLVILLE         BASE_ID = 49
	BASE_SPEKE              BASE_ID = 50
	BASE_SURTUR             BASE_ID = 51
	BASE_THISBURY           BASE_ID = 52
	BASE_TRINSIC            BASE_ID = 53
	BASE_TUCK_S             BASE_ID = 54
	BASE_VALKYRIE           BASE_ID = 55
	BASE_VICTORIA           BASE_ID = 56
	BASE_VISHNU             BASE_ID = 57
	BASE_WICKERTON          BASE_ID = 58
	BASE_DERELICT_BASE      BASE_ID = 59
)

const (
	BT_PLEASURE     BASE_TYPE = 1
	BT_REFINERY     BASE_TYPE = 2
	BT_MINING       BASE_TYPE = 3
	BT_AGRICULTURAL BASE_TYPE = 4
	BT_PIRATE       BASE_TYPE = 5
	BT_SPECIAL      BASE_TYPE = 6
)

type Baseinfo struct {
	Name   string
	Type   BASE_TYPE
	System SYS_ID
}

var Bases = map[BASE_ID]Baseinfo{
	// DATA [8 14 12 16 5 5]
	BASE_ACHILLES:           Baseinfo{Name: "Achilles", Type: BT_MINING, System: SYS_TROY},
	BASE_ANAPOLIS:           Baseinfo{Name: "Anapolis", Type: BT_REFINERY, System: SYS_PERRY},
	BASE_BASQUE:             Baseinfo{Name: "Basque", Type: BT_MINING, System: SYS_PYRENEES},
	BASE_BASRA:              Baseinfo{Name: "Basra", Type: BT_REFINERY, System: SYS_PALAN},
	BASE_BEACONSFIELD:       Baseinfo{Name: "Beaconsfield", Type: BT_REFINERY, System: SYS_AURIGA},
	BASE_BODENSEE:           Baseinfo{Name: "Bodensee", Type: BT_AGRICULTURAL, System: SYS_TINGERHOFF},
	BASE_BURTON:             Baseinfo{Name: "Burton", Type: BT_AGRICULTURAL, System: SYS_JUNCTION},
	BASE_CHARON:             Baseinfo{Name: "Charon", Type: BT_MINING, System: SYS_HYADES},
	BASE_DRAKE:              Baseinfo{Name: "Drake", Type: BT_PIRATE, System: SYS_CAPELLA},
	BASE_EDINBURGH:          Baseinfo{Name: "Edinburgh", Type: BT_REFINERY, System: SYS_NEW_CALEDONIA},
	BASE_EDOM:               Baseinfo{Name: "Edom", Type: BT_AGRICULTURAL, System: SYS_NEW_CONSTANTINOPLE},
	BASE_ELYSIA:             Baseinfo{Name: "Elysia", Type: BT_AGRICULTURAL, System: SYS_AURIGA},
	BASE_EREWHON:            Baseinfo{Name: "Erewhon", Type: BT_PLEASURE, System: SYS_SHANGRI_LA},
	BASE_GLASGOW:            Baseinfo{Name: "Glasgow", Type: BT_REFINERY, System: SYS_NEW_CALEDONIA},
	BASE_GRACCHUS:           Baseinfo{Name: "Gracchus", Type: BT_REFINERY, System: SYS_RAXIS},
	BASE_HECTOR:             Baseinfo{Name: "Hector", Type: BT_MINING, System: SYS_TROY},
	BASE_HEIMDEL:            Baseinfo{Name: "Heimdel", Type: BT_AGRICULTURAL, System: SYS_MIDGARD},
	BASE_HELEN:              Baseinfo{Name: "Helen", Type: BT_AGRICULTURAL, System: SYS_TROY},
	BASE_JOLSON:             Baseinfo{Name: "Jolson", Type: BT_PLEASURE, System: SYS_XXN_1927},
	BASE_JOPLIN:             Baseinfo{Name: "Joplin", Type: BT_REFINERY, System: SYS_XXN_1927},
	BASE_KRONECKER:          Baseinfo{Name: "Kronecker", Type: BT_MINING, System: SYS_REGALLIS},
	BASE_LISACC:             Baseinfo{Name: "Lisacc", Type: BT_MINING, System: SYS_LISACC},
	BASE_LIVERPOOL:          Baseinfo{Name: "Liverpool", Type: BT_REFINERY, System: SYS_NEWCASTLE},
	BASE_MACABEE:            Baseinfo{Name: "Macabee", Type: BT_MINING, System: SYS_NEXUS},
	BASE_MAGDALINE:          Baseinfo{Name: "Magdaline", Type: BT_PLEASURE, System: SYS_PADRE},
	BASE_MATAHARI:           Baseinfo{Name: "Matahari", Type: BT_PLEASURE, System: SYS_ALDEBRAN},
	BASE_MEADOW:             Baseinfo{Name: "Meadow", Type: BT_REFINERY, System: SYS_HIND_S_VARIABLE_N_},
	BASE_MEGIDDO:            Baseinfo{Name: "Megiddo", Type: BT_PIRATE, System: SYS_TELAR},
	BASE_MJOLNAR:            Baseinfo{Name: "Mjolnar", Type: BT_AGRICULTURAL, System: SYS_RAGNAROK},
	BASE_MUNCHEN:            Baseinfo{Name: "Munchen", Type: BT_REFINERY, System: SYS_TINGERHOFF},
	BASE_N1912_1:            Baseinfo{Name: "N1912-1", Type: BT_PLEASURE, System: SYS_DN_N1912},
	BASE_NEW_CONSTANTINOPLE: Baseinfo{Name: "New Constantinople", Type: BT_SPECIAL, System: SYS_NEW_CONSTANTINOPLE},
	BASE_NEW_DETROIT:        Baseinfo{Name: "New Detroit", Type: BT_SPECIAL, System: SYS_NEW_DETROIT},
	BASE_NEW_IBERIA:         Baseinfo{Name: "New Iberia", Type: BT_AGRICULTURAL, System: SYS_PYRENEES},
	BASE_NEW_RENO:           Baseinfo{Name: "New Reno", Type: BT_PLEASURE, System: SYS_ND_57},
	BASE_NITIR:              Baseinfo{Name: "Nitir", Type: BT_AGRICULTURAL, System: SYS_NITIR},
	BASE_OAKHAM:             Baseinfo{Name: "Oakham", Type: BT_PIRATE, System: SYS_PENTONVILLE},
	BASE_OLYMPUS:            Baseinfo{Name: "Olympus", Type: BT_PLEASURE, System: SYS_SAXTOGUE},
	BASE_ORESVILLE:          Baseinfo{Name: "Oresville", Type: BT_AGRICULTURAL, System: SYS_HIND_S_VARIABLE_N_},
	BASE_OXFORD:             Baseinfo{Name: "Oxford", Type: BT_SPECIAL, System: SYS_OXFORD},
	BASE_PALAN:              Baseinfo{Name: "Palan", Type: BT_AGRICULTURAL, System: SYS_PALAN},
	BASE_PERRY_NAVAL_BASE:   Baseinfo{Name: "Perry Naval Base", Type: BT_SPECIAL, System: SYS_PERRY},
	BASE_REMUS:              Baseinfo{Name: "Remus", Type: BT_REFINERY, System: SYS_POLLUX},
	BASE_RILKE:              Baseinfo{Name: "Rilke", Type: BT_REFINERY, System: SYS_VARNUS},
	BASE_RODIN:              Baseinfo{Name: "Rodin", Type: BT_AGRICULTURAL, System: SYS_VARNUS},
	BASE_ROMULUS:            Baseinfo{Name: "Romulus", Type: BT_MINING, System: SYS_CASTOR},
	BASE_RYGANNON:           Baseinfo{Name: "Rygannon", Type: BT_MINING, System: SYS_RYGANNON},
	BASE_SARATOV:            Baseinfo{Name: "Saratov", Type: BT_MINING, System: SYS_PRASEPE},
	BASE_SIVA:               Baseinfo{Name: "Siva", Type: BT_AGRICULTURAL, System: SYS_RIKEL},
	BASE_SMALLVILLE:         Baseinfo{Name: "Smallville", Type: BT_PIRATE, System: SYS_KM_252},
	BASE_SPEKE:              Baseinfo{Name: "Speke", Type: BT_PLEASURE, System: SYS_JUNCTION},
	BASE_SURTUR:             Baseinfo{Name: "Surtur", Type: BT_AGRICULTURAL, System: SYS_SURTUR},
	BASE_THISBURY:           Baseinfo{Name: "Thisbury", Type: BT_REFINERY, System: SYS_MANCHESTER},
	BASE_TRINSIC:            Baseinfo{Name: "Trinsic", Type: BT_AGRICULTURAL, System: SYS_RAXIS},
	BASE_TUCK_S:             Baseinfo{Name: "Tuck's", Type: BT_PIRATE, System: SYS_SHERWOOD},
	BASE_VALKYRIE:           Baseinfo{Name: "Valkyrie", Type: BT_MINING, System: SYS_VALHALLA},
	BASE_VICTORIA:           Baseinfo{Name: "Victoria", Type: BT_AGRICULTURAL, System: SYS_JUNCTION},
	BASE_VISHNU:             Baseinfo{Name: "Vishnu", Type: BT_MINING, System: SYS_RIKEL},
	BASE_WICKERTON:          Baseinfo{Name: "Wickerton", Type: BT_REFINERY, System: SYS_MANCHESTER},
	BASE_DERELICT_BASE:      Baseinfo{Name: "Derelict Base", Type: BT_SPECIAL, System: SYS_DELTA_PRIME},
}
